// TiendaAngularJS/tienda/src/app/carrito/carrito.component.ts
import { Component, OnInit, Injectable } from '@angular/core';
import { ProductosService } from './../productos.service';
import { Router } from '@angular/router';



@Injectable({
    providedIn: 'root'
})
@Component({
  selector: 'app-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css'],
  providers:[ProductosService]

})
export class CarritoComponent implements OnInit {

  numero:number = 0;
  total:number=0;

  productosCarrito = {
      productos : []
  };

  constructor(private productosService:ProductosService, private router:Router) { }

  ngOnInit() {
    this.obtenerNumProdCarrito();
    this.obtenerProductosCarrito();
    this.obtenerTotal();
  }

  obtenerNumProdCarrito(){
    this.productosService.obtenerNumProdCarrito().subscribe((data) => {
      this.numero = data['count'];
    });

  }

  obtenerProductosCarrito(){
    this.productosService.obtenerProductosCarrito().subscribe((data) => {

            for(let prod of data["productos"]){
                for(let prod2 of prod){
                 this.productosCarrito.productos.push(prod2);
               }
            }
    })

  }


  obtenerTotal(){

    let superTotal=0;

    for(let prod of this.productosCarrito.productos){

      superTotal = Number(superTotal) + Number(prod.subtotal);
    }

    return superTotal;

  }

  eliminarProductosCarrito(){
    this.productosService.eliminarProductosCarrito().subscribe((data) => {
        this.numero = 0;
        this.router.navigateByUrl('home');
    })

  }

}

<app-barra></app-barra>

<h3>Carrito de compras</h3>

<div class="row">
    <div class="col l6 m6 s12" >
        <div class="card horizontal" *ngFor="let prod of productosCarrito.productos">
          <div class="card-image">
            <img  src="./assets/img/{{prod.nombre | lowercase}}.jpg" width="300" height="200" />
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h5>{{prod.nombre}}</h5>
              <p><b>Unidades : {{prod.numero}}</b></p>
            </div>
            <div class="card-action">
              <p><b>Subtotal : {{prod.subtotal}}</b></p>
            </div>
          </div>
        </div>
    </div>
    <div class="col l6 m6 s12">
        <h5>Total: $ {{obtenerTotal()}}</h5>
        <div class="row">
          <div class="col l2 m12 s12">
          <button routerLink="/home" class="btn">Cancelar</button>
          </div>
          <div class="col l10 m12 s12">
            <button (click)="eliminarProductosCarrito()" class="btn">Pagar</button>
          </div>
        </div>
    </div>
</div>

// prueba_react/tienda/src/Carrito.jsx
import React from 'react';
import Barra from './Barra.jsx';
import * as request from 'superagent';
import { Link } from "react-router-dom";


class Carrito extends React.Component{

	constructor(){
		super()

		this.state = {
			
			productos:[],
			totalPagar:0
		}

		this.obtenerProductosCarrito();
		this.pagar = this.pagar.bind(this);
	}

	render(){
	
		return(
			<div>
				<Barra />
				<div className="container">
					<h4>Carrito de compras</h4>
					<div className="row">
					<div className="col l6 m6 s12">
					{this.state.productos.map(item => (
					<div className="card horizontal" key={item.nombre}>
      						<div className="card-image">
							<img src={this.obtenerImagen(item.nombre)} alt="img" className="imagen-producto" />	

      						</div>
      						<div className="card-stacked">
        						<div className="card-content">
          							<h5>{item.nombre}</h5>
								<p>Unidades: {item.numero}</p>
								<p>Sub Total: $ {item.subtotal}</p>
       	 						</div>
     						 </div>
    					</div>
					))}
					</div>
					<div className="col l6 m6 s12">
						<h4>Total : {this.state.totalPagar}</h4>
						<Link className="btn" to="/home">Cancelar</Link>&nbsp;
						<button className="btn" onClick={this.pagar}>Pagar</button>
					</div>
					
					</div>
				</div>
			</div>
		)
	}

	obtenerImagen(nombre){
			
		var imagen = require('./img/'+nombre.toLowerCase()+".jpg");
		return imagen; 

	}

	pagar(){
	
		request.get("http://localhost:8080/eliminarProductosCarritoRc").end((err,res)=>{
			
			if(res.ok)
				this.setState({productos:[], totalPagar:0})
		})
	}

	obtenerProductosCarrito(){

		let total = 0;

		request.get('http://localhost:8080/obtenerProductosCarritoRc').end((err,res)=>{
			
			if(!res)
				return;
			
			res.body.productos.forEach((val)=>{
				this.setState({productos:this.state.productos.concat(val)})
		
			
				this.state.productos.forEach((val)=>{
					total = total + parseInt(val.subtotal);
				})
			})
			
			this.setState({totalPagar:total});

		})	
	}

}

export default Carrito;
